In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("G:/Project/Realestate_project/Scripts/india_housing_prices.csv")

In [7]:
df.shape

(250000, 23)

In [8]:
df.head()

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.10,1990,...,35,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.08,2008,...,17,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.05,1997,...,28,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.11,1991,...,34,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.04,2002,...,23,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  str
 2   City                            250000 non-null  str
 3   Locality                        250000 non-null  str
 4   Property_Type                   250000 non-null  str
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  str
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  str
 17  Parking_Space                   250000 non-null  str
 18  Security                        250000 non-null  str
 19  Amenities                       250000 non-null  str
 20  Facing                          250000 non-null  str
 21  Owner_Type                      250000 non-null  str
 22  Availability_Status             250000 non-null  str
dtypes: float64(2), int64(9), str(12)
memory usage: 69.7 MB

In [11]:
df.isnull().sum()

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df["ID"].duplicated().sum()

np.int64(0)

In [14]:
df.describe()

,ID,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,125000.500000,2.999396,2749.813216,254.586854,0.130597,2006.520012,14.966800,15.503004,18.479988,5.499860,5.498016
std,72168.927986,1.415521,1300.606954,141.349921,0.130747,9.808575,8.948047,8.671618,9.808575,2.878639,2.871860
min,1.000000,1.000000,500.000000,10.000000,0.000000,1990.000000,0.000000,1.000000,2.000000,1.000000,1.000000
25%,62500.750000,2.000000,1623.000000,132.550000,0.050000,1998.000000,7.000000,8.000000,10.000000,3.000000,3.000000
50%,125000.500000,3.000000,2747.000000,253.870000,0.090000,2007.000000,15.000000,15.000000,18.000000,5.000000,5.000000
75%,187500.250000,4.000000,3874.000000,376.880000,0.160000,2015.000000,23.000000,23.000000,27.000000,8.000000,8.000000
max,250000.000000,5.000000,5000.000000,500.000000,0.990000,2023.000000,30.000000,30.000000,35.000000,10.000000,10.000000

df.describe().T

In [15]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,250000.0,125000.500000,72168.927986,1.0,62500.75,125000.50,187500.25,250000.00
BHK,250000.0,2.999396,1.415521,1.0,2.00,3.00,4.00,5.00
Size_in_SqFt,250000.0,2749.813216,1300.606954,500.0,1623.00,2747.00,3874.00,5000.00
Price_in_Lakhs,250000.0,254.586854,141.349921,10.0,132.55,253.87,376.88,500.00
Price_per_SqFt,250000.0,0.130597,0.130747,0.0,0.05,0.09,0.16,0.99
Year_Built,250000.0,2006.520012,9.808575,1990.0,1998.00,2007.00,2015.00,2023.00
Floor_No,250000.0,14.966800,8.948047,0.0,7.00,15.00,23.00,30.00
Total_Floors,250000.0,15.503004,8.671618,1.0,8.00,15.00,23.00,30.00
Age_of_Property,250000.0,18.479988,9.808575,2.0,10.00,18.00,27.00,35.00
Nearby_Schools,250000.0,5.499860,2.878639,1.0,3.00,5.00,8.00,10.00
Nearby_Hospitals,250000.0,5.498016,2.871860,1.0,3.00,5.00,8.00,10.00

In [16]:
df.describe(include="object").T

C:\Users\Administrator\AppData\Local\Temp\ipykernel_11760\1274302342.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object").T

                                 count unique                 top    freq
State                           250000     20              Odisha   12681
City                            250000     42          Coimbatore    6461
Locality                        250000    500        Locality_296     567
Property_Type                   250000      3               Villa   83744
Furnished_Status                250000      3         Unfurnished   83408
Public_Transport_Accessibility  250000      3                High   83705
Parking_Space                   250000      2                  No  125456
Security                        250000      2                 Yes  125233
Amenities                       250000    325                Pool   10218
Facing                          250000      4                West   62757
Owner_Type                      250000      3              Broker   83479
Availability_Status             250000      2  Under_Construction  125035

In [17]:
df[df["Price_per_SqFt"] == 0][
    ["ID", "Size_in_SqFt", "Price_in_Lakhs", "Price_per_SqFt"]
].head(10)

        ID  Size_in_SqFt  Price_in_Lakhs  Price_per_SqFt
190    191          4467           11.62             0.0
214    215          3471           17.01             0.0
272    273          4497           21.01             0.0
356    357          3498           12.80             0.0
387    388          4775           18.34             0.0
551    552          3438           15.67             0.0
596    597          4453           18.89             0.0
654    655          4479           14.73             0.0
1023  1024          2888           10.30             0.0
1133  1134          4718           17.80             0.0

In [18]:
(df["Price_per_SqFt"] == 0).sum()

np.int64(2534)

In [19]:
(df["Age_of_Property"] == 2025 - df["Year_Built"]).sum()

np.int64(250000)

In [20]:
(df["Age_of_Property"] != 2025 - df["Year_Built"]).sum()

np.int64(0)

In [21]:
df["Property_Type"].value_counts()

Property_Type
Villa                83744
Independent House    83300
Apartment            82956
Name: count, dtype: int64

In [22]:
df["Amenities"].value_counts().head(20)

Amenities
Pool                     10218
Clubhouse                10010
Garden                   10006
Gym                       9938
Playground                9934
Pool, Playground          2545
Gym, Pool                 2534
Garden, Clubhouse         2524
Gym, Playground           2524
Playground, Gym           2519
Clubhouse, Playground     2516
Playground, Clubhouse     2506
Garden, Gym               2504
Gym, Garden               2500
Garden, Playground        2498
Clubhouse, Garden         2497
Gym, Clubhouse            2496
Pool, Clubhouse           2495
Playground, Garden        2481
Clubhouse, Gym            2470
Name: count, dtype: int64

In [23]:
df.loc[
    df["Price_per_SqFt"] == 0,
    "Price_per_SqFt"
].value_counts()

Price_per_SqFt
0.0    2534
Name: count, dtype: int64

In [26]:
df.loc[
    df["Price_per_SqFt"] == 0,
    ["Price_in_Lakhs", "Size_in_SqFt"]
].describe()

       Price_in_Lakhs  Size_in_SqFt
count     2534.000000   2534.000000
mean        14.962119   3985.990134
std          3.518842    716.472151
min         10.000000   2047.000000
25%         12.012500   3468.250000
50%         14.300000   4109.500000
75%         17.480000   4603.000000
max         24.940000   5000.000000

In [27]:
expected_price_per_sqft = (
    df["Price_in_Lakhs"] / df["Size_in_SqFt"]
)

In [28]:
df.loc[
    df["Price_per_SqFt"] == 0,
    ["Price_in_Lakhs", "Size_in_SqFt"]
].assign(
    Expected_Price_per_SqFt=expected_price_per_sqft
).head(10)

      Price_in_Lakhs  Size_in_SqFt  Expected_Price_per_SqFt
190            11.62          4467                 0.002601
214            17.01          3471                 0.004901
272            21.01          4497                 0.004672
356            12.80          3498                 0.003659
387            18.34          4775                 0.003841
551            15.67          3438                 0.004558
596            18.89          4453                 0.004242
654            14.73          4479                 0.003289
1023           10.30          2888                 0.003566
1133           17.80          4718                 0.003773

In [29]:
df.loc[
    df["Price_per_SqFt"] != 0,
    ["Price_in_Lakhs", "Size_in_SqFt", "Price_per_SqFt"]
].head(10)

   Price_in_Lakhs  Size_in_SqFt  Price_per_SqFt
0          489.76          4740            0.10
1          195.52          2364            0.08
2          183.79          3642            0.05
3          300.29          2741            0.11
4          182.90          4823            0.04
5          135.28          3500            0.04
6          318.12          4826            0.07
7          141.39          4252            0.03
8          189.16          2678            0.07
9          187.42          1393            0.13

In [31]:
4*0.25

1.0

In [33]:
df["Price_per_SqFt"] = (
    df["Price_in_Lakhs"] / df["Size_in_SqFt"]
)

In [34]:
(df["Price_per_SqFt"] == 0).sum()

np.int64(0)

In [35]:
Q1 = df["Price_in_Lakhs"].quantile(0.25)
Q3 = df["Price_in_Lakhs"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower limit:", lower_limit)
print("Upper limit:", upper_limit)

Q1: 132.55
Q3: 376.88
IQR: 244.32999999999998
Lower limit: -233.945
Upper limit: 743.375

In [36]:
outliers = df[
    (df["Price_in_Lakhs"] < lower_limit) |
    (df["Price_in_Lakhs"] > upper_limit)
]

print("Number of potential outliers:", len(outliers))

Number of potential outliers: 0

In [38]:
def check_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    
    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR
    
    outliers = df[
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    ]
    
    print("Column:", column)
    print("Q1:", Q1)
    print("Q3:", Q3)
    print("IQR:", IQR)
    print("Lower limit:", lower_limit)
    print("Upper limit:", upper_limit)
    print("Number of potential outliers:", len(outliers))

In [39]:
check_outliers_iqr(df, "Size_in_SqFt")

Column: Size_in_SqFt
Q1: 1623.0
Q3: 3874.0
IQR: 2251.0
Lower limit: -1753.5
Upper limit: 7250.5
Number of potential outliers: 0

In [40]:
check_outliers_iqr(df, "Price_per_SqFt")

Column: Price_per_SqFt
Q1: 0.04802839710440703
Q3: 0.1598738851727982
IQR: 0.11184548806839117
Lower limit: -0.11973983499817972
Upper limit: 0.32764211727538495
Number of potential outliers: 19723

In [42]:
outliers_price_sqft = df[
    df["Price_per_SqFt"] > upper_limit
]

outliers_price_sqft[
    ["ID", "City", "Property_Type",
     "Size_in_SqFt", "Price_in_Lakhs",
     "Price_per_SqFt"]
].head(20)

Empty DataFrame
Columns: [ID, City, Property_Type, Size_in_SqFt, Price_in_Lakhs, Price_per_SqFt]
Index: []

In [43]:
Q1 = df["Price_per_SqFt"].quantile(0.25)
Q3 = df["Price_per_SqFt"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers_price_sqft = df[
    df["Price_per_SqFt"] > upper_limit
]

print("Upper limit:", upper_limit)
print("Number of outliers:", len(outliers_price_sqft))

Upper limit: 0.32764211727538495
Number of outliers: 19723

In [44]:
outliers_price_sqft[
    ["ID", "City", "Property_Type",
     "Size_in_SqFt", "Price_in_Lakhs",
     "Price_per_SqFt"]
].head(20)

,ID,City,Property_Type,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt
10,11,Warangal,Independent House,665,324.24,0.487579
20,21,Noida,Independent House,1270,475.78,0.374630
46,47,Chennai,Villa,641,300.29,0.468471
49,50,Bilaspur,Villa,733,438.74,0.598554
51,52,Haridwar,Independent House,556,308.46,0.554784
53,54,Ranchi,Villa,855,335.30,0.392164
57,58,Jodhpur,Villa,581,457.94,0.788193
61,62,Chennai,Villa,1106,421.32,0.380940
65,66,Bhopal,Apartment,890,439.52,0.493843
67,68,Indore,Apartment,502,486.68,0.969482
73,74,Ahmedabad,Independent House,978,418.76,0.428180
74,75,Raipur,Villa,1041,357.84,0.343746
99,100,Kolkata,Apartment,509,375.00,0.736739
105,106,Warangal,Independent House,517,262.28,0.507311
168,169,New Delhi,Apartment,653,483.31,0.740138
169,170,Bilaspur,Apartment,758,470.13,0.620224
180,181,Bilaspur,Apartment,741,499.57,0.674184
183,184,Vijayawada,Independent House,600,498.79,0.831317
207,208,Silchar,Apartment,911,466.06,0.511592
230,231,Bangalore,Apartment,999,342.81,0.343153

In [45]:
check_outliers_iqr(df, "BHK")

Column: BHK
Q1: 2.0
Q3: 4.0
IQR: 2.0
Lower limit: -1.0
Upper limit: 7.0
Number of potential outliers: 0

In [46]:
check_outliers_iqr(df, "Year_Built")

Column: Year_Built
Q1: 1998.0
Q3: 2015.0
IQR: 17.0
Lower limit: 1972.5
Upper limit: 2040.5
Number of potential outliers: 0

In [47]:
check_outliers_iqr(df, "Floor_No")

Column: Floor_No
Q1: 7.0
Q3: 23.0
IQR: 16.0
Lower limit: -17.0
Upper limit: 47.0
Number of potential outliers: 0

In [48]:
check_outliers_iqr(df, "Total_Floors")

Column: Total_Floors
Q1: 8.0
Q3: 23.0
IQR: 15.0
Lower limit: -14.5
Upper limit: 45.5
Number of potential outliers: 0

In [49]:
check_outliers_iqr(df, "Age_of_Property")

Column: Age_of_Property
Q1: 10.0
Q3: 27.0
IQR: 17.0
Lower limit: -15.5
Upper limit: 52.5
Number of potential outliers: 0

In [50]:
check_outliers_iqr(df, "Nearby_Schools")

Column: Nearby_Schools
Q1: 3.0
Q3: 8.0
IQR: 5.0
Lower limit: -4.5
Upper limit: 15.5
Number of potential outliers: 0

In [51]:
check_outliers_iqr(df, "Nearby_Hospitals")

Column: Nearby_Hospitals
Q1: 3.0
Q3: 8.0
IQR: 5.0
Lower limit: -4.5
Upper limit: 15.5
Number of potential outliers: 0

In [52]:
(df["Floor_No"] > df["Total_Floors"]).sum()

np.int64(116304)

In [53]:
df.loc[
    df["Floor_No"] > df["Total_Floors"],
    ["ID", "City", "Property_Type", "Floor_No", "Total_Floors"]
].head(20)

    ID        City      Property_Type  Floor_No  Total_Floors
0    1     Chennai          Apartment        22             1
1    2        Pune  Independent House        21            20
4    5      Jaipur              Villa         3             2
5    6    Durgapur          Apartment        27             1
6    7  Coimbatore  Independent House        16             5
7    8    Bilaspur  Independent House        24             4
8    9   New Delhi              Villa        23            16
12  13      Nagpur  Independent House         9             1
13  14   New Delhi  Independent House        13             4
14  15     Lucknow          Apartment        26            18
16  17     Silchar              Villa        15            10
17  18    Dehradun              Villa        14             8
18  19        Pune              Villa        10             5
21  22    Bilaspur              Villa        17             7
24  25        Gaya          Apartment        25             1
26  27    Ludhiana  Independent House         9             5
28  29   Ahmedabad  Independent House        14             9
30  31   Faridabad          Apartment        15             1
31  32    Amritsar              Villa        29            25
38  39     Chennai          Apartment        21             4

In [54]:
(df["Floor_No"] <= df["Total_Floors"]).value_counts()

True     133696
False    116304
Name: count, dtype: int64

In [55]:
pd.crosstab(df["Floor_No"], df["Total_Floors"]).head(10)

Total_Floors,1,2,3,4,5,6,7,8,9,10,...,21,22,23,24,25,26,27,28,29,30
Floor_No,,,,,,,,,,,,,,,,,,,,,
0,260,307,275,281,282,270,258,293,266,277,...,292,250,246,284,290,277,234,277,264,280
1,270,262,271,288,258,248,252,266,281,277,...,284,262,245,306,276,285,259,303,277,262
2,306,256,277,260,261,291,269,273,285,265,...,242,302,262,284,238,279,277,272,259,258
3,260,269,268,262,288,278,266,262,255,270,...,271,253,270,292,259,291,274,222,244,291
4,262,277,254,283,293,248,235,258,265,305,...,223,249,284,270,269,282,282,271,245,239
5,273,272,292,267,287,255,255,236,299,292,...,258,265,254,290,248,272,268,268,270,271
6,265,300,304,282,278,258,284,297,281,274,...,257,271,249,281,254,260,268,267,261,304
7,259,280,269,235,272,274,227,280,272,266,...,273,258,289,326,266,287,277,292,264,247
8,253,293,317,254,255,253,264,268,265,262,...,274,268,254,245,305,263,293,301,267,279
9,231,279,251,276,288,304,253,257,256,264,...,276,279,257,293,278,275,286,253,280,276

In [56]:
(df["Floor_No"] - df["Total_Floors"]).describe()

count    250000.000000
mean         -0.536204
std          12.453238
min         -30.000000
25%          -9.000000
50%          -1.000000
75%           8.000000
max          29.000000
dtype: float64

In [58]:
df["Floor_Data_Issue"] = df["Floor_No"] > df["Total_Floors"]

In [59]:
df["Floor_Data_Issue"].value_counts()

Floor_Data_Issue
False    133696
True     116304
Name: count, dtype: int64

In [60]:
pd.crosstab(
    df["Property_Type"],
    df["Floor_Data_Issue"],
    normalize="index"
) * 100

Floor_Data_Issue       False      True
Property_Type
Apartment          53.422296  46.577704
Independent House  53.595438  46.404562
Villa              53.417558  46.582442

In [61]:
df["Floor_Data_Issue"] = df["Floor_No"] > df["Total_Floors"]

In [63]:
df["Floor_No"].value_counts().sort_index()

Floor_No
0     8203
1     8076
2     8125
3     8073
4     7949
5     8174
6     8166
7     8106
8     8149
9     8064
10    7975
11    8041
12    8077
13    7990
14    8108
15    8154
16    8051
17    8197
18    8145
19    7868
20    8283
21    7991
22    7876
23    7912
24    7869
25    8056
26    8114
27    8091
28    7966
29    8075
30    8076
Name: count, dtype: int64

In [64]:
df["Floor_No"].min(), df["Floor_No"].max()

(np.int64(0), np.int64(30))

In [ ]:
(df["Floor_No"] < 0).sum()

np.int64(0)

In [67]:
df["Total_Floors"].min(), df["Total_Floors"].max()

(np.int64(1), np.int64(30))

In [68]:
(df["Total_Floors"] < 1).sum()

np.int64(0)

In [69]:
df["BHK"].min(), df["BHK"].max()

(np.int64(1), np.int64(5))

In [70]:
(df["BHK"] < 1).sum()

np.int64(0)

In [71]:
df["Size_in_SqFt"].min(), df["Size_in_SqFt"].max()

(np.int64(500), np.int64(5000))

In [72]:
(df["Size_in_SqFt"] <= 0).sum()

np.int64(0)

In [73]:
df["Price_in_Lakhs"].min(), df["Price_in_Lakhs"].max()

(np.float64(10.0), np.float64(500.0))

In [74]:
(df["Price_in_Lakhs"] <= 0).sum()

np.int64(0)

In [75]:
df["Year_Built"].min(), df["Year_Built"].max()

(np.int64(1990), np.int64(2023))

In [76]:
(df["Year_Built"] > 2025).sum()

np.int64(0)

In [77]:
df["Furnished_Status"].value_counts()

Furnished_Status
Unfurnished       83408
Semi-furnished    83374
Furnished         83218
Name: count, dtype: int64

In [78]:
df["Public_Transport_Accessibility"].value_counts()

Public_Transport_Accessibility
High      83705
Low       83287
Medium    83008
Name: count, dtype: int64

In [79]:
df["Parking_Space"].value_counts()

Parking_Space
No     125456
Yes    124544
Name: count, dtype: int64

In [80]:
df["Security"].value_counts()

Security
Yes    125233
No     124767
Name: count, dtype: int64

In [81]:
df["Amenities"].value_counts().head(20)

Amenities
Pool                     10218
Clubhouse                10010
Garden                   10006
Gym                       9938
Playground                9934
Pool, Playground          2545
Gym, Pool                 2534
Garden, Clubhouse         2524
Gym, Playground           2524
Playground, Gym           2519
Clubhouse, Playground     2516
Playground, Clubhouse     2506
Garden, Gym               2504
Gym, Garden               2500
Garden, Playground        2498
Clubhouse, Garden         2497
Gym, Clubhouse            2496
Pool, Clubhouse           2495
Playground, Garden        2481
Clubhouse, Gym            2470
Name: count, dtype: int64

In [82]:
df.head(5)

,ID,State,City,Locality,Property_Type,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,...,Nearby_Schools,Nearby_Hospitals,Public_Transport_Accessibility,Parking_Space,Security,Amenities,Facing,Owner_Type,Availability_Status,Floor_Data_Issue
0,1,Tamil Nadu,Chennai,Locality_84,Apartment,1,4740,489.76,0.103325,1990,...,10,3,High,No,No,"Playground, Gym, Garden, Pool, Clubhouse",West,Owner,Ready_to_Move,True
1,2,Maharashtra,Pune,Locality_490,Independent House,3,2364,195.52,0.082707,2008,...,8,1,Low,No,Yes,"Playground, Clubhouse, Pool, Gym, Garden",North,Builder,Under_Construction,True
2,3,Punjab,Ludhiana,Locality_167,Apartment,2,3642,183.79,0.050464,1997,...,9,8,Low,Yes,No,"Clubhouse, Pool, Playground, Gym",South,Broker,Ready_to_Move,False
3,4,Rajasthan,Jodhpur,Locality_393,Independent House,2,2741,300.29,0.109555,1991,...,5,7,High,Yes,Yes,"Playground, Clubhouse, Gym, Pool, Garden",North,Builder,Ready_to_Move,False
4,5,Rajasthan,Jaipur,Locality_466,Villa,4,4823,182.90,0.037922,2002,...,4,9,Low,No,Yes,"Playground, Garden, Gym, Pool, Clubhouse",East,Builder,Ready_to_Move,True

In [83]:
df.describe

<bound method NDFrame.describe of             ID        State       City      Locality      Property_Type  BHK  \
0            1   Tamil Nadu    Chennai   Locality_84          Apartment    1
1            2  Maharashtra       Pune  Locality_490  Independent House    3
2            3       Punjab   Ludhiana  Locality_167          Apartment    2
3            4    Rajasthan    Jodhpur  Locality_393  Independent House    2
4            5    Rajasthan     Jaipur  Locality_466              Villa    4
...        ...          ...        ...           ...                ...  ...
249995  249996      Gujarat  Ahmedabad  Locality_187  Independent House    5
249996  249997   Tamil Nadu    Chennai  Locality_348          Apartment    1
249997  249998    Telangana   Warangal  Locality_225              Villa    4
249998  249999       Odisha    Cuttack  Locality_138              Villa    1
249999  250000      Haryana    Gurgaon  Locality_268  Independent House    3

        Size_in_SqFt  Price_in_Lakhs  Price_per_SqFt  Year_Built  ...  \
0               4740          489.76        0.103325        1990  ...
1               2364          195.52        0.082707        2008  ...
2               3642          183.79        0.050464        1997  ...
3               2741          300.29        0.109555        1991  ...
4               4823          182.90        0.037922        2002  ...
...              ...             ...             ...         ...  ...
249995          1995          274.75        0.137719        1995  ...
249996          2293           13.40        0.005844        2013  ...
249997          2910          236.94        0.081423        2003  ...
249998          1149          141.66        0.123290        2007  ...
249999          4313          199.69        0.046300        1990  ...

       Nearby_Schools  Nearby_Hospitals  Public_Transport_Accessibility  \
0                  10                 3                            High
1                   8                 1                             Low
2                   9                 8                             Low
3                   5                 7                            High
4                   4                 9                             Low
...               ...               ...                             ...
249995              8                 6                             Low
249996              8                10                             Low
249997             10                 4                            High
249998              3                 7                             Low
249999             10                 6                          Medium

        Parking_Space  Security                                 Amenities  \
0                  No        No  Playground, Gym, Garden, Pool, Clubhouse
1                  No       Yes  Playground, Clubhouse, Pool, Gym, Garden
2                 Yes        No          Clubhouse, Pool, Playground, Gym
3                 Yes       Yes  Playground, Clubhouse, Gym, Pool, Garden
4                  No       Yes  Playground, Garden, Gym, Pool, Clubhouse
...               ...       ...                                       ...
249995             No        No  Playground, Garden, Gym, Clubhouse, Pool
249996             No        No                                Playground
249997            Yes       Yes                                Playground
249998            Yes       Yes                     Playground, Gym, Pool
249999             No        No                               Gym, Garden

       Facing Owner_Type Availability_Status Floor_Data_Issue
0        West      Owner       Ready_to_Move             True
1       North    Builder  Under_Construction             True
2       South     Broker       Ready_to_Move            False
3       North    Builder       Ready_to_Move            False
4        East    Builder       Ready_to_Move             True
...       ...        ...                 ...              ...
249995   East     Broker  Under_Construction             True
249996  South     Broker       Ready_to_Move            False
249997  South    Builder  Under_Construction            False
249998  South      Owner       Ready_to_Move             True
249999  South      Owner  Under_Construction            False

[250000 rows x 24 columns]>

In [84]:
df.columns

Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status', 'Floor_Data_Issue'],
      dtype='str')

In [86]:
df["Price_in_Lakhs"] * 100000 / df["Size_in_SqFt"]
calculated_pps = (
    df["Price_in_Lakhs"] * 100000
    / df["Size_in_SqFt"]
)

(df["Price_per_SqFt"] - calculated_pps).abs().describe()

count    250000.000000
mean      13058.151193
std       13071.719762
min         202.245169
25%        4802.791682
50%        9244.655146
75%       15987.228643
max       99181.008180
dtype: float64

In [90]:
check = df[
    ["ID", "Size_in_SqFt", "Price_in_Lakhs", "Price_per_SqFt"]
].copy()

check["Calculated_Price_per_SqFt"] = (
    check["Price_in_Lakhs"] * 100000
    / check["Size_in_SqFt"]
)
check.head(10)

   ID  Size_in_SqFt  Price_in_Lakhs  Price_per_SqFt  Calculated_Price_per_SqFt
0   1          4740          489.76        0.103325               10332.489451
1   2          2364          195.52        0.082707                8270.727580
2   3          3642          183.79        0.050464                5046.403075
3   4          2741          300.29        0.109555               10955.490697
4   5          4823          182.90        0.037922                3792.245490
5   6          3500          135.28        0.038651                3865.142857
6   7          4826          318.12        0.065918                6591.794447
7   8          4252          141.39        0.033253                3325.258702
8   9          2678          189.16        0.070635                7063.480209
9  10          1393          187.42        0.134544               13454.414932

In [91]:
df["Price_per_SqFt"] = (
    df["Price_in_Lakhs"] * 100000
    / df["Size_in_SqFt"]
)
df[["Price_in_Lakhs", "Size_in_SqFt", "Price_per_SqFt"]].head()

   Price_in_Lakhs  Size_in_SqFt  Price_per_SqFt
0          489.76          4740    10332.489451
1          195.52          2364     8270.727580
2          183.79          3642     5046.403075
3          300.29          2741    10955.490697
4          182.90          4823     3792.245490

In [92]:
calculated_pps = (
    df["Price_in_Lakhs"] * 100000
    / df["Size_in_SqFt"]
)

(df["Price_per_SqFt"] - calculated_pps).abs().max()

np.float64(0.0)

In [93]:
check_outliers_iqr(df, "Price_per_SqFt")

Column: Price_per_SqFt
Q1: 4802.839710440703
Q3: 15987.388517279822
IQR: 11184.548806839119
Lower limit: -11973.983499817974
Upper limit: 32764.2117275385
Number of potential outliers: 19723

In [94]:
df = df.drop(columns=["Floor_Data_Issue"])
df.shape

(250000, 23)

In [95]:
df.shape

(250000, 23)

In [96]:
df.isnull().sum().sum()

np.int64(0)

In [97]:
df.duplicated().sum()

np.int64(0)

In [98]:
df["Price_per_SqFt"].min(), df["Price_per_SqFt"].max()

(np.float64(202.24719101123594), np.float64(99182.0))

In [99]:
df.columns

Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='str')

In [100]:
df["ID"].nunique(), len(df)

(250000, 250000)

In [101]:
df["ID"].is_unique

True

In [102]:
df.to_csv("property_data_updated.csv", index=False)

In [103]:
import os

os.path.exists("property_data_updated.csv")

True

In [106]:
df['Price_in_Lakhs'].max()

np.float64(500.0)

In [112]:
df["BHK"].max()

np.int64(5)

In [113]:
numeric_cols = df.select_dtypes(include="number")

correlation_matrix = numeric_cols.corr()

correlation_matrix

,ID,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals
ID,1.000000,-0.001718,-0.002293,-0.001636,-0.001328,0.002734,-0.000214,0.003382,-0.002734,-0.001203,0.001429
BHK,-0.001718,1.000000,-0.001033,-0.000980,0.001138,0.000917,0.001263,-0.002862,-0.000917,-0.000762,0.001162
Size_in_SqFt,-0.002293,-0.001033,1.000000,-0.002529,-0.614610,0.004135,-0.002775,-0.003451,-0.004135,0.001966,-0.001695
Price_in_Lakhs,-0.001636,-0.000980,-0.002529,1.000000,0.555781,0.002714,-0.001719,0.001283,-0.002714,0.000155,-0.002769
Price_per_SqFt,-0.001328,0.001138,-0.614610,0.555781,1.000000,-0.001330,-0.001904,0.004161,0.001330,-0.000058,-0.000122
Year_Built,0.002734,0.000917,0.004135,0.002714,-0.001330,1.000000,-0.000686,0.003452,-1.000000,-0.000591,-0.002719
Floor_No,-0.000214,0.001263,-0.002775,-0.001719,-0.001904,-0.000686,1.000000,0.001169,0.000686,-0.000635,0.001428
Total_Floors,0.003382,-0.002862,-0.003451,0.001283,0.004161,0.003452,0.001169,1.000000,-0.003452,-0.003093,-0.005867
Age_of_Property,-0.002734,-0.000917,-0.004135,-0.002714,0.001330,-1.000000,0.000686,-0.003452,1.000000,0.000591,0.002719
Nearby_Schools,-0.001203,-0.000762,0.001966,0.000155,-0.000058,-0.000591,-0.000635,-0.003093,0.000591,1.000000,-0.002246
Nearby_Hospitals,0.001429,0.001162,-0.001695,-0.002769,-0.000122,-0.002719,0.001428,-0.005867,0.002719,-0.002246,1.000000