In [ ]:
####Importing and reading data
import pandas as pd

df = pd.read_csv("G:/Project/Realestate_project/Scripts/india_housing_prices.csv")
####data size and column
print(df.shape)
print(df.columns)

(250000, 23)
Index(['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK',
       'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built',
       'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property',
       'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility',
       'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type',
       'Availability_Status'],
      dtype='str')

In [2]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 23 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              250000 non-null  int64
 1   State                           250000 non-null  str
 2   City                            250000 non-null  str
 3   Locality                        250000 non-null  str
 4   Property_Type                   250000 non-null  str
 5   BHK                             250000 non-null  int64
 6   Size_in_SqFt                    250000 non-null  int64
 7   Price_in_Lakhs                  250000 non-null  float64
 8   Price_per_SqFt                  250000 non-null  float64
 9   Year_Built                      250000 non-null  int64
 10  Furnished_Status                250000 non-null  str
 11  Floor_No                        250000 non-null  int64
 12  Total_Floors                    250000 non-null  int64
 13  Age_of_Property                 250000 non-null  int64
 14  Nearby_Schools                  250000 non-null  int64
 15  Nearby_Hospitals                250000 non-null  int64
 16  Public_Transport_Accessibility  250000 non-null  str
 17  Parking_Space                   250000 non-null  str
 18  Security                        250000 non-null  str
 19  Amenities                       250000 non-null  str
 20  Facing                          250000 non-null  str
 21  Owner_Type                      250000 non-null  str
 22  Availability_Status             250000 non-null  str
dtypes: float64(2), int64(9), str(12)
memory usage: 69.7 MB

ID                                0
State                             0
City                              0
Locality                          0
Property_Type                     0
BHK                               0
Size_in_SqFt                      0
Price_in_Lakhs                    0
Price_per_SqFt                    0
Year_Built                        0
Furnished_Status                  0
Floor_No                          0
Total_Floors                      0
Age_of_Property                   0
Nearby_Schools                    0
Nearby_Hospitals                  0
Public_Transport_Accessibility    0
Parking_Space                     0
Security                          0
Amenities                         0
Facing                            0
Owner_Type                        0
Availability_Status               0
dtype: int64

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df["ID"].nunique()

250000

In [5]:
df[df["Floor_No"] > df["Total_Floors"]][["ID", "Floor_No", "Total_Floors"]].head(20)

    ID  Floor_No  Total_Floors
0    1        22             1
1    2        21            20
4    5         3             2
5    6        27             1
6    7        16             5
7    8        24             4
8    9        23            16
12  13         9             1
13  14        13             4
14  15        26            18
16  17        15            10
17  18        14             8
18  19        10             5
21  22        17             7
24  25        25             1
26  27         9             5
28  29        14             9
30  31        15             1
31  32        29            25
38  39        21             4

In [6]:
(df["Floor_No"] > df["Total_Floors"]).sum()

np.int64(116304)

In [7]:
print(df[["Floor_No", "Total_Floors"]].describe())

            Floor_No   Total_Floors
count  250000.000000  250000.000000
mean       14.966800      15.503004
std         8.948047       8.671618
min         0.000000       1.000000
25%         7.000000       8.000000
50%        15.000000      15.000000
75%        23.000000      23.000000
max        30.000000      30.000000

In [10]:
df.loc[df["Total_Floors"] < df["Floor_No"], "Total_Floors"] = df["Floor_No"]

In [11]:
(df["Floor_No"] > df["Total_Floors"]).sum()

np.int64(0)

In [12]:
df["Price"] = df["Price_in_Lakhs"] * 100000

In [14]:
df[["Price_in_Lakhs", "Price"]].head()

   Price_in_Lakhs       Price
0          489.76  48976000.0
1          195.52  19552000.0
2          183.79  18379000.0
3          300.29  30029000.0
4          182.90  18290000.0

np.float64(99181.01)

In [18]:
df["Price_per_SqFt"] = df["Price"] / df["Size_in_SqFt"]

In [19]:
df[[
    "Price",
    "Size_in_SqFt",
    "Price_per_SqFt"
]].head()

        Price  Size_in_SqFt  Price_per_SqFt
0  48976000.0          4740    10332.489451
1  19552000.0          2364     8270.727580
2  18379000.0          3642     5046.403075
3  30029000.0          2741    10955.490697
4  18290000.0          4823     3792.245490

In [20]:
df.describe()

,ID,BHK,Size_in_SqFt,Price_in_Lakhs,Price_per_SqFt,Year_Built,Floor_No,Total_Floors,Age_of_Property,Nearby_Schools,Nearby_Hospitals,Price
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,2.500000e+05
mean,125000.500000,2.999396,2749.813216,254.586854,13058.281776,2006.520012,14.966800,20.323928,18.479988,5.499860,5.498016,2.545869e+07
std,72168.927986,1.415521,1300.606954,141.349921,13071.850480,9.808575,8.948047,7.192554,9.808575,2.878639,2.871860,1.413499e+07
min,1.000000,1.000000,500.000000,10.000000,202.247191,1990.000000,0.000000,1.000000,2.000000,1.000000,1.000000,1.000000e+06
25%,62500.750000,2.000000,1623.000000,132.550000,4802.839710,1998.000000,7.000000,15.000000,10.000000,3.000000,3.000000,1.325500e+07
50%,125000.500000,3.000000,2747.000000,253.870000,9244.747594,2007.000000,15.000000,22.000000,18.000000,5.000000,5.000000,2.538700e+07
75%,187500.250000,4.000000,3874.000000,376.880000,15987.388517,2015.000000,23.000000,26.000000,27.000000,8.000000,8.000000,3.768800e+07
max,250000.000000,5.000000,5000.000000,500.000000,99182.000000,2023.000000,30.000000,30.000000,35.000000,10.000000,10.000000,5.000000e+07

In [21]:
(df["Age_of_Property"] != (2025 - df["Year_Built"])).sum()

np.int64(0)

In [22]:
for col in df.select_dtypes(include="object").columns:
    print(f"\n{col}:")
    print(df[col].unique())

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6044\358977919.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

State:
<ArrowStringArray>
[    'Tamil Nadu',    'Maharashtra',         'Punjab',      'Rajasthan',
    'West Bengal',   'Chhattisgarh',          'Delhi',      'Jharkhand',
      'Telangana',      'Karnataka',  'Uttar Pradesh',          'Assam',
    'Uttarakhand',          'Bihar',        'Gujarat',        'Haryana',
 'Andhra Pradesh', 'Madhya Pradesh',         'Kerala',         'Odisha']
Length: 20, dtype: str

City:
<ArrowStringArray>
[       'Chennai',           'Pune',       'Ludhiana',        'Jodhpur',
         'Jaipur',       'Durgapur',     'Coimbatore',       'Bilaspur',
      'New Delhi',         'Ranchi',       'Warangal',      'Bangalore',
         'Nagpur',        'Lucknow',        'Silchar',       'Dehradun',
          'Noida',           'Gaya',     'Jamshedpur',      'Ahmedabad',
      'Hyderabad',      'Faridabad',       'Amritsar',        'Kolkata',
         'Dwarka', 'Vishakhapatnam',         'Bhopal',         'Indore',
       'Haridwar',         'Mysore',          'Patna',         'Raipur',
     'Vijayawada',     'Trivandrum',          'Kochi',          'Surat',
        'Gurgaon',      'Mangalore',        'Cuttack',    'Bhubaneswar',
       'Guwahati',         'Mumbai']
Length: 42, dtype: str

Locality:
<ArrowStringArray>
[ 'Locality_84', 'Locality_490', 'Locality_167', 'Locality_393',
 'Locality_466', 'Locality_246', 'Locality_254', 'Locality_232',
 'Locality_122',  'Locality_75',
 ...
 'Locality_264', 'Locality_127', 'Locality_147', 'Locality_267',
 'Locality_361', 'Locality_216', 'Locality_427', 'Locality_253',
 'Locality_429',  'Locality_72']
Length: 500, dtype: str

Property_Type:
<ArrowStringArray>
['Apartment', 'Independent House', 'Villa']
Length: 3, dtype: str

Furnished_Status:
<ArrowStringArray>
['Furnished', 'Unfurnished', 'Semi-furnished']
Length: 3, dtype: str

Public_Transport_Accessibility:
<ArrowStringArray>
['High', 'Low', 'Medium']
Length: 3, dtype: str

Parking_Space:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Security:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

Amenities:
<ArrowStringArray>
['Playground, Gym, Garden, Pool, Clubhouse',
 'Playground, Clubhouse, Pool, Gym, Garden',
         'Clubhouse, Pool, Playground, Gym',
 'Playground, Clubhouse, Gym, Pool, Garden',
 'Playground, Garden, Gym, Pool, Clubhouse',
                    'Playground, Clubhouse',
            'Clubhouse, Garden, Playground',
         'Gym, Pool, Clubhouse, Playground',
            'Garden, Clubhouse, Playground',
       'Clubhouse, Playground, Garden, Gym',
 ...
 'Clubhouse, Pool, Gym, Garden, Playground',
 'Gym, Pool, Playground, Clubhouse, Garden',
 'Gym, Pool, Garden, Playground, Clubhouse',
      'Clubhouse, Pool, Playground, Garden',
      'Clubhouse, Playground, Garden, Pool',
             'Clubhouse, Pool, Garden, Gym',
 'Garden, Gym, Clubhouse, Pool, Playground',
 'Gym, Playground, Pool, Garden, Clubhouse',
      'Garden, Playground, Clubhouse, Pool',
 'Clubhouse, Gym, Playground, Pool, Garden']
Length: 325, dtype: str

Facing:
<ArrowStringArray>
['West', 'North', 'South', 'East']
Length: 4, dtype: str

Owner_Type:
<ArrowStringArray>
['Owner', 'Builder', 'Broker']
Length: 3, dtype: str

Availability_Status:
<ArrowStringArray>
['Ready_to_Move', 'Under_Construction']
Length: 2, dtype: str

In [23]:
for col in df.select_dtypes(include="str").columns:
    print(col, df[col].str.strip().equals(df[col]))

State True
City True
Locality True
Property_Type True
Furnished_Status True
Public_Transport_Accessibility True
Parking_Space True
Security True
Amenities True
Facing True
Owner_Type True
Availability_Status True

In [24]:
df["Future_Price_5Y"] = df["Price"] * (1 + 0.08) ** 5

In [25]:
df[["Price", "Future_Price_5Y"]].head()

        Price  Future_Price_5Y
0  48976000.0     7.196181e+07
1  19552000.0     2.872830e+07
2  18379000.0     2.700478e+07
3  30029000.0     4.412245e+07
4  18290000.0     2.687401e+07

In [26]:
median_price_sqft = df["Price_per_SqFt"].median()
median_price_sqft

np.float64(9244.747593959637)

In [27]:
df["Price_SqFt_Score"] = (
    df["Price_per_SqFt"] <= median_price_sqft
).astype(int)

In [28]:
df["Price_SqFt_Score"].value_counts()

Price_SqFt_Score
0    125000
1    125000
Name: count, dtype: int64

In [29]:
df["BHK_Score"] = (df["BHK"] >= 3).astype(int)

In [30]:
df["BHK_Score"].value_counts()

BHK_Score
1    149989
0    100011
Name: count, dtype: int64

In [31]:
df["Ready_Move_Score"] = (
    df["Availability_Status"] == "Ready_to_Move"
).astype(int)

In [32]:
df["Ready_Move_Score"].value_counts()

Ready_Move_Score
0    125035
1    124965
Name: count, dtype: int64

In [33]:
df["Investment_Score"] = (
    df["Price_SqFt_Score"]
    + df["BHK_Score"]
    + df["Ready_Move_Score"]
)

In [34]:
df["Investment_Score"].value_counts().sort_index()

Investment_Score
0     25050
1     87439
2    100018
3     37493
Name: count, dtype: int64

In [35]:
df["Good_Investment"] = (
    df["Investment_Score"] >= 2
).astype(int)

In [36]:
df["Good_Investment"].value_counts()

Good_Investment
1    137511
0    112489
Name: count, dtype: int64

In [37]:
df.drop(
    columns=[
        "Price_SqFt_Score",
        "BHK_Score",
        "Ready_Move_Score",
        "Investment_Score"
    ],
    inplace=True
)

In [38]:
df["Amenities"].unique()

<ArrowStringArray>
['Playground, Gym, Garden, Pool, Clubhouse',
 'Playground, Clubhouse, Pool, Gym, Garden',
         'Clubhouse, Pool, Playground, Gym',
 'Playground, Clubhouse, Gym, Pool, Garden',
 'Playground, Garden, Gym, Pool, Clubhouse',
                    'Playground, Clubhouse',
            'Clubhouse, Garden, Playground',
         'Gym, Pool, Clubhouse, Playground',
            'Garden, Clubhouse, Playground',
       'Clubhouse, Playground, Garden, Gym',
 ...
 'Clubhouse, Pool, Gym, Garden, Playground',
 'Gym, Pool, Playground, Clubhouse, Garden',
 'Gym, Pool, Garden, Playground, Clubhouse',
      'Clubhouse, Pool, Playground, Garden',
      'Clubhouse, Playground, Garden, Pool',
             'Clubhouse, Pool, Garden, Gym',
 'Garden, Gym, Clubhouse, Pool, Playground',
 'Gym, Playground, Pool, Garden, Clubhouse',
      'Garden, Playground, Clubhouse, Pool',
 'Clubhouse, Gym, Playground, Pool, Garden']
Length: 325, dtype: str

In [39]:
amenities = set()

for value in df["Amenities"]:
    for amenity in value.split(","):
        amenities.add(amenity.strip())

print(amenities)
print("Total amenities:", len(amenities))

{'Garden', 'Gym', 'Playground', 'Clubhouse', 'Pool'}
Total amenities: 5

In [40]:
amenities = ["Garden", "Gym", "Playground", "Clubhouse", "Pool"]

for amenity in amenities:
    df[f"Amenity_{amenity}"] = (
        df["Amenities"].str.contains(amenity, regex=False)
    ).astype(int)

In [41]:
df[[
    "Amenities",
    "Amenity_Garden",
    "Amenity_Gym",
    "Amenity_Playground",
    "Amenity_Clubhouse",
    "Amenity_Pool"
]].head()

,Amenities,Amenity_Garden,Amenity_Gym,Amenity_Playground,Amenity_Clubhouse,Amenity_Pool
0,"Playground, Gym, Garden, Pool, Clubhouse",1,1,1,1,1
1,"Playground, Clubhouse, Pool, Gym, Garden",1,1,1,1,1
2,"Clubhouse, Pool, Playground, Gym",0,1,1,1,1
3,"Playground, Clubhouse, Gym, Pool, Garden",1,1,1,1,1
4,"Playground, Garden, Gym, Pool, Clubhouse",1,1,1,1,1

In [42]:
print(df.columns.tolist())

['ID', 'State', 'City', 'Locality', 'Property_Type', 'BHK', 'Size_in_SqFt', 'Price_in_Lakhs', 'Price_per_SqFt', 'Year_Built', 'Furnished_Status', 'Floor_No', 'Total_Floors', 'Age_of_Property', 'Nearby_Schools', 'Nearby_Hospitals', 'Public_Transport_Accessibility', 'Parking_Space', 'Security', 'Amenities', 'Facing', 'Owner_Type', 'Availability_Status', 'Price', 'Future_Price_5Y', 'Good_Investment', 'Amenity_Garden', 'Amenity_Gym', 'Amenity_Playground', 'Amenity_Clubhouse', 'Amenity_Pool']

In [43]:
df.to_csv(
    "G:/Project/Realestate_project/Scripts/property_data_updated.csv",
    index=False
)

NameError: name 'X' is not defined